theme: jekyll-theme-cayman
title: FlatDB
description: High-performance, fault-tolerant, distributed database as simple as a flat text file.
github:
  repository_url: https://github.com/chemist777/flatdb
